### ISSUE TITLE
Could you please give me a detailed document on openwms

### ISSUE THREAD

**Issue by shyding** [openwms/org.openwms.common.service#62]
Could you please give me a detailed document on openwms

**Comment by openwms** [comment]
Start on the main Confluence site https://openwms.atlassian.net/wiki/home
In particular for the OpenWMS.org Common Service I suggest studying the README on the repository page (https://github.com/openwms/org.openwms.common.service). There is a link to the microservice homepage (https://openwms.github.io/org.openwms.common.service/). Each microservice has its own documentation site and also its own Confluence space with further information. 

main page
 |-> microservice repository README
     |-> microservice website
           |-> microservice Confluence space
